/* ---------------------------------------------------------------------------
 * Building md-editor.
 *
 * The output is a single file, `dist/index.html`, holding everything: CSS,
 * JavaScript, dependencies. No external resource is referenced, so the page
 * behaves identically served over HTTP or opened from `file://` after a plain
 * copy -- which is what lets a user drop the server entirely.
 *
 * The inline script is allowed by the CSP through its SHA-256 digest, computed
 * here over the exact bytes that will be written into the page. Change one byte
 * afterwards and the browser refuses to run it.
 *
 *   node build.mjs           build dist/
 *   node build.mjs --serve   build, then serve dist/ on :8080 with the same
 *                            headers as the production container
 * ------------------------------------------------------------------------- */

import * as esbuild from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { createServer } from "node:http";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const dist = resolve(root, "dist");
const serve = process.argv.includes("--serve");

/* --- 1. JavaScript bundle ------------------------------------------------ */

const bundle = await esbuild.build({
  entryPoints: [resolve(root, "src/app.js")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2021"],
  charset: "utf8",
  legalComments: "eof", // dependency MIT licences stay in the file
  write: false,
  logLevel: "info",
});

// `</script` can only appear in valid JavaScript inside a string, a regular
// expression or a comment, so escaping it never changes the semantics -- and it
// stops the HTML parser from closing the tag in the middle of the bundle.
const js = bundle.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const css = await readFile(resolve(root, "src/styles.css"), "utf8");

/* --- 2. Content Security Policy ------------------------------------------ */

const scriptHash = createHash("sha256").update(js, "utf8").digest("base64");

// `frame-ancestors` is ignored inside a <meta> tag: it only takes effect as an
// HTTP header, hence the generated csp.conf for nginx. The rest is duplicated
// in the document so the protection travels with the downloaded file.
const CSP_DIRECTIVES = [
  "default-src 'none'",
  `script-src 'sha256-${scriptHash}'`,
  "style-src 'unsafe-inline'",
  "img-src data: blob:",
  "font-src data:",
  "connect-src 'none'",
  "form-action 'none'",
  "base-uri 'none'",
];

const cspMeta = CSP_DIRECTIVES.join("; ");

// No `sandbox` directive here: it would add almost nothing on top of
// `default-src 'none'` and would break the File System Access API, which direct
// file saving relies on.
const cspHeader = [...CSP_DIRECTIVES, "frame-ancestors 'none'"].join("; ");

/* --- 3. Final document --------------------------------------------------- */

// `data-theme` is deliberately absent: the stylesheet then follows
// `prefers-color-scheme`, and the script sets the attribute as soon as it runs.
//
// The <body> holds nothing but an empty container: the whole interface is built
// by the script. That is what makes rebuilding the standalone file from the DOM
// faithful to the original, with no risk of embedding the user's document.
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="${cspMeta}">
<meta name="referrer" content="no-referrer">
<meta name="color-scheme" content="light dark">
<meta name="description" content="A Markdown editor that runs entirely in the browser.">
<title>Markdown editor</title>
<style id="app-css">${css}</style>
</head>
<body>
<div id="app"></div>
<script id="app-js">${js}</script>
</body>
</html>
`;

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await writeFile(resolve(dist, "index.html"), html, "utf8");

// Fragment included by nginx: keeps the header and the document perfectly in
// step, script digest included.
await writeFile(
  resolve(dist, "csp.conf"),
  `# Generated by build.mjs -- do not edit by hand.\n` +
  `add_header Content-Security-Policy "${cspHeader}" always;\n`,
  "utf8",
);

// Digest of the delivered file: the value to publish with each release so a
// user can verify the page they were actually served.
const fileHash = createHash("sha256").update(html, "utf8").digest("hex");
await writeFile(resolve(dist, "index.html.sha256"), `${fileHash}  index.html\n`, "utf8");

const kb = (n) => (n / 1024).toFixed(1) + " kB";
console.log(`\n  dist/index.html   ${kb(Buffer.byteLength(html))}  (js ${kb(Buffer.byteLength(js))}, css ${kb(Buffer.byteLength(css))})`);
console.log(`  sha256            ${fileHash}`);
console.log(`  script-src        'sha256-${scriptHash}'\n`);

/* --- 4. Development server ----------------------------------------------- */

if (serve) {
  const port = Number(process.env.PORT || 8080);
  const body = Buffer.from(html, "utf8");

  createServer((req, res) => {
    if (req.method !== "GET" && req.method !== "HEAD") {
      res.writeHead(405, { Allow: "GET, HEAD" }).end();
      return;
    }
    res.writeHead(200, {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Length": body.length,
      "Content-Security-Policy": cspHeader,
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "no-referrer",
      "Permissions-Policy": "geolocation=(), microphone=(), camera=(), interest-cohort=()",
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Resource-Policy": "same-origin",
      "Cache-Control": "no-cache",
    });
    res.end(req.method === "HEAD" ? undefined : body);
  }).listen(port, () => {
    console.log(`  Development server: http://localhost:${port}\n`);
  });
}
